services:
  # Backend Service
  - type: web
    name: tif3-backend
    env: python
    buildCommand: cd backend/clubmember && pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate
    startCommand: cd backend/clubmember && gunicorn clubmember.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: DJANGO_SETTINGS_MODULE
        value: clubmember.settings
      - key: DATABASE_URL
        fromDatabase:
          name: tif3-db
          property: connectionString
  
  # Frontend Service
  - type: web
    name: tif3-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: tif3-db
    databaseName: tif3
    user: tif3
